using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication6.Models
{
    public enum Color

    {
        [Display(Name = "Beyaz")]
        White = 1,
        [Display(Name = "Kahverengi")]
        Brown = 2,
        [Display(Name = "Gri ")]
        Gray = 3,
        [Display(Name = "Mavi")]
        Blue = 4,
        [Display(Name = "Kırmızı ")]
        Red = 5,
        [Display(Name = "Siyah ")]
        Black = 6,
        [Display(Name = "Bej")]
        Beige = 7,
        [Display(Name = "Yeşil")]
        Green = 8,
        [Display(Name = "Pembe ")]
        Pink = 9,
        [Display(Name = "Metalik ")]
        Metallic = 10,
        [Display(Name = "Karışım")]
        Mix = 11,
        [Display(Name = "Antrasit")]
        Anthracite = 12,
        [Display(Name = "Lila")]
        Lila = 13,
        [Display(Name = "Claret")]
        Claret = 14,
        [Display(Name = "Fildişi")]
        Ivory = 15,
        [Display(Name = "Cotto")]
        Cotto = 16,
        [Display(Name = "Zeytin")]
        Olive = 17,
        [Display(Name = "Toz")]
        Powder = 18,
        [Display(Name = "Sis Gülü")]
        FogWhite = 19,
        [Display(Name = "Süper Beyaz")]
        SuperWhite = 20,
        [Display(Name = "Somon")]
        Salmon = 21,
        [Display(Name = "Platin")]
        Platinum = 22,
        [Display(Name = "Altın")]
        Gold = 23,
        [Display(Name = "Bakır")]
        Copper = 24,
        [Display(Name = "Vino")]
        Vino = 25,
        [Display(Name = "Nero")]
        Nero = 26,
        [Display(Name = "Zümrüt")]
        Emerald = 27,
        [Display(Name = "Vizon")]
        Vizon = 28,
        [Display(Name = "Nar Kırmızısı")]
        PomegranateFlower = 29,
        [Display(Name = "Hardal")]
        Mustard = 30,
        [Display(Name = "Tarçın")]
        Cinnamon = 31,
        [Display(Name = "Kobalt Mavisi")]
        CobaltBlue = 32,
        [Display(Name = "Lacivert")]
        NavyBlue = 33,
        [Display(Name = "Classico")]
        Classico = 34,
        [Display(Name = "Mocha")]
        Mocha = 35,
        [Display(Name = "Erik")]
        Plum = 36,
        [Display(Name = "Bronz")]
        Bronze = 37,
        [Display(Name = "Villa")]
        Villa = 38,
        [Display(Name = "Oksit Yayan")]
        OxideYellow = 39,
        [Display(Name = "Kil")]
        Clay = 40,
        [Display(Name = "Karbon")]
        Carbon = 41,
        [Display(Name = "Hesseli")]
        Hessian = 42,
        [Display(Name = "Natura")]
        Natura = 43,
        [Display(Name = "Nute")]
        Nute = 44,
        [Display(Name = "Badem")]
        Almond = 45,
        [Display(Name = "Kum")]
        Sand = 46,
        [Display(Name = "Cappucino")]
        Cappucino = 47,
        [Display(Name = "Rust")]
        Rust = 48,
        [Display(Name = "Oksit")]
        Oxide = 49,
        [Display(Name = "Kış Ağaçları")]
        Winterwood = 50,
        [Display(Name = "Kafe")]
        Cafe = 51,
        [Display(Name = "Meşe")]
        Oak = 52,
        [Display(Name = "Noce")]
        Noce = 53,
        [Display(Name = "Kiraz")]
        Cherry = 54,
        [Display(Name = "Armut")]
        Pear = 55,
        [Display(Name = "Venge")]
        Wenge = 56,
        [Display(Name = "Füme")]
        Smoked = 57,
        [Display(Name = "Merbau")]
        Merbau = 58,
        [Display(Name = "Çimento")]
        Cement = 59,
        [Display(Name = "Beton")]
        Beton = 60,
        [Display(Name = "Ahşap")]
        Wood = 61,
        [Display(Name = "Taba")]
        Taba = 62,
        [Display(Name = "Günbatımı")]
        Sunset = 63,
        [Display(Name = "Rosso")]
        Rosso = 64,
        [Display(Name = "Rustik")]
        Rustic = 65,
        [Display(Name = "Argento")]
        Argento = 66,
        [Display(Name = "Safari")]
        Safari = 67,
        [Display(Name = "Füzyon")]
        Fusion = 68,
        [Display(Name = "Doğal")]
        Natural = 69,
        [Display(Name = "Sis")]
        Mist = 70,
        [Display(Name = "Buz")]
        Ice = 71,
        [Display(Name = "Mika")]
        Mica = 72,
        [Display(Name = "Dünya")]
        Earth = 73,
        [Display(Name = "Sonbahar")]
        Autumn = 74,
        [Display(Name = "Su")]
        Aqua = 75,
        [Display(Name = "Lav")]
        Lava = 76,
        [Display(Name = "Krem")]
        Cream = 77,
        [Display(Name = "Çoklu")]
        Multi = 78,
        [Display(Name = "LightGrey ")]
        LightGrey = 79,
        [Display(Name = "Açık Bej")]
        OnBeige = 80,
        [Display(Name = "Bianco")]
        Bianco = 81,
        [Display(Name = "Buz Beyazı")]
        IceWhite = 82,
        [Display(Name = "Bergama")]
        Pergamon = 83,
        [Display(Name = "Gece Mavisi")]
        NightBlue = 84,
        [Display(Name = "Ceviz")]
        Walnut = 85,
        [Display(Name = "Birch")]
        Birch = 86,
        [Display(Name = "Verde")]
        Verde = 87,
        [Display(Name = "Renk Karışımı")]
        ColorMix = 88,
        [Display(Name = "Kemik")]
        Bone = 89

    }
}